


# start proxy by `npm run proxy`
RINGCENTRAL_APP_SERVER: https://xxxx.ngrok.io

# You can add "Webhook" app from Glip app list to get static webhook url
# STATIC_WEBHOOK: https://hooks.glip.com/webhook/xxxx

GITHUB_CLIENT_ID: xxxx
GITHUB_CLIENT_SECRET: yyyyy
GITHUB_SCOPES: repo admin:repo_hook read:user read:org

## Make sure you change it in production
SERVER_SECRET: 123ee53ttsdf@@$ds2dgdgas@sfsdgdhdh

# server app path, in case you want to use a special path like /app
APP_HOME: /app

## for postgres, could be postgresql://db-username:db_passowrd@yyyy.xxxxx.us-east-1.rds.amazonaws.com:5432/dbname
RINGCENTRAL_DATABASE_CONNECTION_URI: sqlite://./db.sqlite

## admin makesure you change it in production
RINGCENTRAL_ADMIN_USERNAME: admin232323457876
RINGCENTRAL_ADMIN_PASSWORD: admin234234423

## database dialect,
## By default it is not needed
## when use `dynamodb`, will requires dynamodb and AWS settings, and RINGCENTRAL_CHATBOT_DATABASE_CONNECTION_URI will be ignored
DIALECT: dynamodb
# AWS_ACCESS_KEY_ID: 
# AWS_SECRET_ACCESS_KEY: 
AWS_REGION: us-east-1
DYNAMODB_TABLE_PREFIX: RC

## when set, will use local DYNAMODB, remember you have to start your own dynamodb local server
## example: http://localhost:8000
# DYNAMODB_LOCALHOST: